### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by theo-mc** [AlexvZyl/nvim#1]
how do u get your lualine to stick to the very bottom of the window, i cant find it in your config

**Comment by AlexvZyl** [comment]
I think this is what you are looking for: https://github.com/AlexvZyl/nvim/blob/main/lua%2Falex%2Fplugins%2Fui%2Flualine.lua#L236

**Comment by theo-mc** [comment]
yeah the "globalstatus = true," line does it i think, however i changed my colorscheme (ironically to ur nordic one) and realized the real problem i was having was a fontsize/terminal size mismatch causing an unusable line. thanks anyway tho.

**Comment by AlexvZyl** [comment]
Great, glad I could help :)
